### ISSUE TITLE
Missing link to deployed version

### ISSUE THREAD

**Issue by linusblom** [chas-academy/08-api-mashup-GabrielvonPlaten#1]
Please provide link to deployed version in README.md

**Comment by GabrielvonPlaten** [comment]
The latest version should be live now.
I still have to implement a widget into my project.

**Comment by linusblom** [comment]
I also need the link in README.md :)

**Comment by GabrielvonPlaten** [comment]
I just noticed my mistake. I thought I commented on my trello-clone repo, which I have updated a few days ago.
I'm still working on the API-mashup, which is the reason I have not put the deployed link to README.md. 
I'm sorry for the inconvenience.

**Comment by linusblom** [comment]
Ahh, I see, just close this issue when the deployed version is ready. I check the trello repo instead.

**Comment by linusblom** [comment]
@GabrielvonPlaten
